/* ============================================================
   Mathyu's Solutions — content dictionary
   Keys are looked up by `data-i18n` attributes on elements.
   Modes: tech-es (default, in DOM) | tech-en | biz-es | biz-en
   ============================================================ */

const CONTENT = {

/* ---------------- TECH · ENGLISH ---------------- */
"tech-en": {
  "nav.services": "Services", "nav.process": "Process", "nav.cases": "Cases", "nav.pricing": "Plans", "nav.contact": "Contact", "nav.cta": "Get a quote",
  "aud.biz": "Business", "aud.tech": "Technical",

  "hero.eyebrow": "Software consultancy · Lima, Peru",
  "hero.h1a": "We build", "hero.h1b": "serious software", "hero.h1c": "for teams that ship fast.",
  "hero.lead": "Web, mobile (iOS & Android) and AI with DevOps baked in and deployment on AWS, Azure or GCP. From idea to product, with maintainable code and real metrics.",
  "hero.cta1": "Start a project", "hero.cta2": "See services",
  "hero.m1": "Years of experience", "hero.m2": "Clouds supported", "hero.m3": "Core stacks", "hero.m4": "Monitoring & support",

  "trust.label": "// Stack & cloud",

  "svc.eyebrow": "01 · Services", "svc.title": "Five practices. One team. One contract.",
  "svc.desc": "We cover the full cycle: digital product, native mobile, AI capabilities, infrastructure and continuous operation. No middlemen.",
  "svc.tab1": "Web Apps", "svc.tab2": "Mobile · iOS & Android", "svc.tab3": "AI Applications", "svc.tab4": "DevOps & SRE", "svc.tab5": "Cloud Engineering",
  "svc.stackLabel": "Typical stack",

  "svc.web.eyebrow": "Web Product", "svc.web.h": "SPAs, dashboards and platforms that scale with your business.",
  "svc.web.p": "Fast frontends, solid backends and day-one observability. System design ready for integrations, multi-tenant and real growth.",
  "svc.web.f1": "React, Next.js and server-first architectures", "svc.web.f2": "REST/GraphQL APIs · Node, Python or Go",
  "svc.web.f3": "Auth, payments, multi-tenant and RBAC from day one", "svc.web.f4": "Core Web Vitals, technical SEO and A/B testing",

  "svc.mob.eyebrow": "Native mobile + cross-platform", "svc.mob.h": "Apps that feel native on iOS and Android.",
  "svc.mob.p": "Native (Swift / Kotlin) when performance matters, React Native / Flutter when speed wins. We ship to stores, not demos.",
  "svc.mob.f1": "Swift / SwiftUI for iOS · Kotlin / Compose for Android", "svc.mob.f2": "React Native and Flutter for faster delivery",
  "svc.mob.f3": "Push, deep links, biometrics, in-app payments", "svc.mob.f4": "Store publishing, code-signing and automated release trains",

  "svc.ai.eyebrow": "Applied AI", "svc.ai.h": "AI that lives in your product, not in a demo.",
  "svc.ai.p": "Copilots, agents and RAG pipelines on your data, with guardrails, evaluation and cost control. No magic, all measurable.",
  "svc.ai.f1": "RAG, semantic search and tool-using agents", "svc.ai.f2": "Fine-tuning and self-hosted open-source models",
  "svc.ai.f3": "LLM evaluation, observability and guardrails", "svc.ai.f4": "Integration with OpenAI, Anthropic, Bedrock or Vertex",

  "svc.dev.eyebrow": "DevOps · SRE · Platform", "svc.dev.h": "CI/CD, IaC and observability included by default.",
  "svc.dev.p": "Not an extra layer: every project ships with pipelines, infrastructure as code and metrics from the first commit. Fewer surprises in prod.",
  "svc.dev.f1": "GitHub Actions, GitLab CI or Jenkins · per-env pipelines", "svc.dev.f2": "Terraform and Pulumi · versioned infrastructure",
  "svc.dev.f3": "Kubernetes, ECS and serverless when it fits", "svc.dev.f4": "Datadog, Grafana, Sentry · real SLOs and alerts",

  "svc.cloud.eyebrow": "Cloud · AWS · Azure · GCP", "svc.cloud.h": "Multi-cloud without lock-in: the right cloud for each workload.",
  "svc.cloud.p": "Pragmatic, secure architectures with audited cost. We migrate, modernize and operate workloads on all three majors.",
  "svc.cloud.f1": "Landing zones, IAM, networking and security baseline", "svc.cloud.f2": "Migrations and modernizations (lift, shift & re-arch)",
  "svc.cloud.f3": "FinOps · cost visibility and continuous optimization", "svc.cloud.f4": "Disaster recovery, backups and compliance",

  "proc.eyebrow": "02 · Process", "proc.title": "From brief to production, drama-free.",
  "proc.desc": "A measurable process: five phases with clear deliverables, focused meetings and shippable code from week one.",
  "proc.n1": "01 / DISCOVER", "proc.n2": "02 / DESIGN", "proc.n3": "03 / BUILD", "proc.n4": "04 / SHIP", "proc.n5": "05 / OPERATE",
  "proc.s1h": "Technical discovery", "proc.s1p": "We map goal, users and constraints. Architecture doc and phased plan.",
  "proc.s2h": "Design & prototype", "proc.s2p": "UX/UI, design system and clickable prototype validated with real users before writing code.",
  "proc.s3h": "Sprint build", "proc.s3p": "1–2 week sprints, demos, progress metrics and peer-reviewed code.",
  "proc.s4h": "Ship", "proc.s4p": "CI/CD to production on AWS, Azure or GCP. Load and security testing, assisted go-live.",
  "proc.s5h": "Operate", "proc.s5p": "SLOs, 24/7 monitoring, cost optimization and continuous evolution roadmap.",

  "case.eyebrow": "03 · Case studies", "case.title": "Real products. Real users.",
  "case.desc": "A small selection of projects we've shipped: a circular-economy platform in Peru, a bilingual park site in Italy, and a native iOS app on the App Store.",
  "case.b1": "Sustainability · Web", "case.b2": "Tourism · Web · IT/EN", "case.b3": "Productivity · iOS",
  "case.c1p": "Web platform for a circular-economy company: construction waste management and eco-materials in Peru.",
  "case.c2p": "Bilingual (IT/EN) website for an Italian gardens & butterflies association in Basilicata: bookings, subscriptions and gallery.",
  "case.c3p": "Native iOS app: smart alarms based on calendar events. In 2 taps you pick the event and how many minutes before to wake up.",

  "testi.eyebrow": "04 · Testimonials", "testi.title": "What the teams we work with say.",
  "testi.desc": "Long-term relationships with CTOs, founders and product leads. Few clients, deep commitment.",
  "testi.q1": "They felt the product as their own from week one. Delivered in three months what had been stuck for a year.",
  "testi.q2": "DevOps included changed everything: we stopped firefighting and started iterating product.",
  "testi.q3": "The AI team took us from prototype to live in production with eval metrics even finance could understand.",

  "price.eyebrow": "05 · Plans", "price.title": "Clear collaboration models.",
  "price.desc": "We work fixed-scope, dedicated team or retainer. No hidden fees, with full visibility over effort.",
  "price.from": "from", "price.month": "/ mo", "price.custom": "Custom",
  "price.p1h": "Launchpad", "price.p1t": "Fixed scope project", "price.p1d": "Market-ready web or mobile MVP, with baseline DevOps and cloud deploy.",
  "price.p1f1": "1 product · web or mobile", "price.p1f2": "Design + dev + deploy", "price.p1f3": "CI/CD and cloud included", "price.p1f4": "Delivered in 6–10 weeks",
  "price.p1c": "Request proposal",
  "price.p2h": "Scale", "price.p2t": "Dedicated team", "price.p2d": "Multidisciplinary squad embedded with your team: product + dev + DevOps + AI if needed.",
  "price.p2f1": "Squad of 3–5 senior people", "price.p2f2": "Sprints, demos and weekly metrics", "price.p2f3": "Mobile + web + AI + cloud", "price.p2f4": "3-month minimum commitment",
  "price.p2c": "Reserve squad",
  "price.p3h": "Enterprise", "price.p3t": "Retainer & SRE", "price.p3d": "Continuous operation and evolution of critical platforms, with SLOs, on-call and FinOps.",
  "price.p3f1": "Per-service SLOs and SLAs", "price.p3f2": "24/7 on-call and support", "price.p3f3": "Multi-cloud FinOps", "price.p3f4": "Quarterly joint roadmap",
  "price.p3c": "Talk to a partner",

  "ct.eyebrow": "06 · Contact", "ct.title": "Tell us about your project.",
  "ct.desc": "We reply in under 24 business hours with an honest first read on scope, time and cost.",
  "ct.info": "// Direct contact", "ct.h": "Let's talk, no middlemen.", "ct.p": "Write, call or schedule a meeting. We work remote, based in Lima — Peru.",
  "ct.lblPhone": "Phone · WhatsApp", "ct.lblMail": "Email", "ct.lblRuc": "RUC",
  "ct.fName": "Your name", "ct.fEmail": "Email", "ct.fCompany": "Company", "ct.fService": "Service",
  "ct.fOpt1": "Web application", "ct.fOpt2": "Mobile app (iOS / Android)", "ct.fOpt3": "AI solution", "ct.fOpt4": "DevOps / SRE", "ct.fOpt5": "Cloud (AWS · Azure · GCP)", "ct.fOpt6": "Not sure · I need advice",
  "ct.fMsg": "Tell us about your project", "ct.fNote": "We reply in < 24 business hours", "ct.fSend": "Send message",

  "foot.blurb": "Software consultancy · web, mobile, AI and cloud. We build serious products for teams that ship fast.",
  "foot.s1": "Services", "foot.s1a": "Web Apps", "foot.s1b": "Mobile iOS & Android", "foot.s1c": "AI Applications", "foot.s1d": "DevOps & SRE", "foot.s1e": "Cloud Engineering",
  "foot.s2": "Company", "foot.s2a": "Process", "foot.s2b": "Cases", "foot.s2c": "Plans", "foot.s2d": "Contact",
  "foot.s3": "Contact", "foot.rights": "All rights reserved",

  "mod.eyebrow": "// Quick quote", "mod.h": "Let's start your project.", "mod.p": "Leave your info and a technical partner reaches out in under 24 business hours.",
  "mod.brief": "Short brief", "mod.send": "Send & schedule call"
},

/* ---------------- BIZ · SPANISH ---------------- */
"biz-es": {
  "nav.services": "Servicios", "nav.process": "Cómo trabajamos", "nav.cases": "Proyectos", "nav.pricing": "Precios", "nav.contact": "Contacto", "nav.cta": "Pedir cotización",
  "aud.biz": "Negocio", "aud.tech": "Técnico",

  "hero.eyebrow": "Software para hacer crecer tu negocio · Lima, Perú",
  "hero.h1a": "Hacemos", "hero.h1b": "el software", "hero.h1c": "que tu negocio necesita para crecer.",
  "hero.lead": "Páginas web, tiendas online, apps móviles y automatización con inteligencia artificial. Te acompañamos desde la idea hasta el día en que tus clientes ya lo están usando.",
  "hero.cta1": "Conversemos de tu proyecto", "hero.cta2": "Ver lo que hacemos",
  "hero.m1": "Años acompañando negocios", "hero.m2": "Sectores que atendemos", "hero.m3": "Tipos de soluciones", "hero.m4": "Soporte continuo",

  "trustBiz.label": "// Sectores que atendemos",
  "trustBiz.c1": "Comercio", "trustBiz.c2": "Restaurantes", "trustBiz.c3": "Servicios profesionales",
  "trustBiz.c4": "Salud & clínicas", "trustBiz.c5": "Educación", "trustBiz.c6": "Inmobiliaria",
  "trustBiz.c7": "Logística & delivery", "trustBiz.c8": "Startups & emprendedores",

  "bh.eyebrow": "// Lo que recibes",
  "bh.title": "Tu negocio, listo para internet.",
  "bh.i1t": "Tu página o tienda online", "bh.i1d": "Diseñada para vender, rápida y fácil de actualizar.",
  "bh.i2t": "Tu app para celular",      "bh.i2d": "En App Store y Google Play, lista para tus clientes.",
  "bh.i3t": "IA que te ahorra tiempo",  "bh.i3d": "Chatbots, automatizaciones y respuestas automáticas en WhatsApp.",
  "bh.i4t": "Soporte cuando lo necesites","bh.i4d": "Mantenimiento, mejoras y respaldo continuo. Sin sorpresas.",
  "bh.p1": "años", "bh.p2": "semanas típicas", "bh.p3": "Soporte continuo",

  "svc.eyebrow": "01 · Lo que hacemos", "svc.title": "Cinco soluciones para hacer crecer tu negocio.",
  "svc.desc": "Te acompañamos de principio a fin: idea, diseño, desarrollo, lanzamiento y soporte. Sin intermediarios y sin letra chica.",
  "svc.tab1": "Páginas y tiendas web", "svc.tab2": "Apps para celular", "svc.tab3": "Automatización con IA", "svc.tab4": "Mantenimiento y soporte", "svc.tab5": "Tu negocio en la nube",
  "svc.stackLabel": "Lo que incluye",

  "svc.web.eyebrow": "Tu presencia web", "svc.web.h": "Una página o tienda online hecha para vender.",
  "svc.web.p": "Diseño moderno, rápido y fácil de actualizar. Lista para celulares, optimizada para Google y con todas las integraciones que tu negocio necesita.",
  "svc.web.f1": "Página web institucional o tienda online completa",
  "svc.web.f2": "Pagos online con Niubiz, Culqi, MercadoPago o Izipay",
  "svc.web.f3": "Panel para que tú mismo actualices precios y productos",
  "svc.web.f4": "Posicionamiento en Google y velocidad de carga rápida",
  "svc.web.b1": "Página institucional", "svc.web.b2": "Tienda online", "svc.web.b3": "Panel de administración",
  "svc.web.b4": "Pagos online", "svc.web.b5": "SEO en Google", "svc.web.b6": "Hosting incluido",

  "svc.mob.eyebrow": "Apps para celular", "svc.mob.h": "Tu negocio en el bolsillo de tus clientes.",
  "svc.mob.p": "Apps profesionales para iPhone y Android: pedidos, reservas, fidelización, delivery o lo que tu negocio necesite. Publicamos en las tiendas oficiales.",
  "svc.mob.f1": "App para iPhone (App Store) y Android (Play Store)",
  "svc.mob.f2": "Notificaciones, pagos in-app y login con huella o cara",
  "svc.mob.f3": "Publicación en las tiendas y soporte de versiones",
  "svc.mob.f4": "Diseño que tus clientes entienden de inmediato",
  "svc.mob.b1": "App para iPhone", "svc.mob.b2": "App para Android", "svc.mob.b3": "Notificaciones push",
  "svc.mob.b4": "Login biométrico", "svc.mob.b5": "Pagos in-app", "svc.mob.b6": "Publicación en stores",

  "svc.ai.eyebrow": "Inteligencia artificial práctica", "svc.ai.h": "Automatiza tareas y atiende a tus clientes 24/7.",
  "svc.ai.p": "Chatbots que sí entienden, asistentes que responden por WhatsApp, sistemas que clasifican documentos, recomiendan productos o resumen reuniones. IA aplicada, no humo.",
  "svc.ai.f1": "Chatbots inteligentes para WhatsApp y tu página web",
  "svc.ai.f2": "Búsqueda inteligente sobre tus documentos y correos",
  "svc.ai.f3": "Resumen y clasificación automática de información",
  "svc.ai.f4": "Análisis de datos y predicciones de ventas",
  "svc.ai.b1": "Chatbot WhatsApp", "svc.ai.b2": "Atención 24/7", "svc.ai.b3": "Resumen de correos",
  "svc.ai.b4": "Búsqueda inteligente", "svc.ai.b5": "Predicción de ventas", "svc.ai.b6": "Recomendaciones",

  "svc.dev.eyebrow": "Mantenimiento sin sorpresas", "svc.dev.h": "Tu sistema funcionando siempre, sin que tengas que preocuparte.",
  "svc.dev.p": "Mantenemos tu sitio, app y sistemas operando 24/7. Detectamos problemas antes que tus clientes y nos encargamos de las actualizaciones y respaldos.",
  "svc.dev.f1": "Monitoreo continuo y respaldos automáticos",
  "svc.dev.f2": "Actualizaciones de seguridad cada mes",
  "svc.dev.f3": "Respuesta rápida si algo falla",
  "svc.dev.f4": "Reportes mensuales claros, en español",
  "svc.dev.b1": "Monitoreo 24/7", "svc.dev.b2": "Respaldos automáticos", "svc.dev.b3": "Actualizaciones",
  "svc.dev.b4": "Seguridad", "svc.dev.b5": "Reportes mensuales", "svc.dev.b6": "Respuesta rápida",

  "svc.cloud.eyebrow": "Tu negocio en la nube", "svc.cloud.h": "Tus sistemas, datos y archivos seguros y accesibles.",
  "svc.cloud.p": "Migramos tu negocio a la nube de los grandes (AWS, Azure o Google). Tus datos respaldados, tu equipo trabajando desde cualquier lugar y costos controlados.",
  "svc.cloud.f1": "Migración de tus sistemas a la nube",
  "svc.cloud.f2": "Respaldo seguro de toda tu información",
  "svc.cloud.f3": "Acceso desde cualquier lugar y dispositivo",
  "svc.cloud.f4": "Control mensual de costos sin sorpresas",
  "svc.cloud.b1": "Migración a la nube", "svc.cloud.b2": "Respaldo seguro", "svc.cloud.b3": "Acceso remoto",
  "svc.cloud.b4": "Control de costos", "svc.cloud.b5": "Correo corporativo", "svc.cloud.b6": "Archivos compartidos",

  "proc.eyebrow": "02 · Cómo trabajamos", "proc.title": "Un proceso simple, sin enredos técnicos.",
  "proc.desc": "Cinco pasos claros. Tú decides cuánto involucrarte y nosotros nos encargamos de la parte técnica.",
  "proc.n1": "01 / ESCUCHAMOS", "proc.n2": "02 / DISEÑAMOS", "proc.n3": "03 / CONSTRUIMOS", "proc.n4": "04 / LANZAMOS", "proc.n5": "05 / ACOMPAÑAMOS",
  "proc.s1h": "Te escuchamos", "proc.s1p": "Conversamos sobre tu negocio, tus clientes y qué quieres lograr. Te entregamos una propuesta clara con plazos y costos.",
  "proc.s2h": "Diseñamos", "proc.s2p": "Te mostramos cómo se verá tu sitio o app antes de empezar a desarrollar. Ajustamos hasta que te guste.",
  "proc.s3h": "Construimos", "proc.s3p": "Programamos en etapas y te mostramos avances cada semana. Tú revisas y das tu visto bueno.",
  "proc.s4h": "Lanzamos", "proc.s4p": "Subimos todo a la nube y publicamos en las tiendas si es app. Acompañamos el lanzamiento contigo.",
  "proc.s5h": "Acompañamos", "proc.s5p": "Te damos soporte, actualizaciones y mejoras. Si algo falla, lo arreglamos rápido.",

  "case.eyebrow": "03 · Proyectos", "case.title": "Productos reales que ya están en uso.",
  "case.desc": "Una pequeña muestra de proyectos que hemos lanzado: una plataforma de economía circular en Perú, un sitio bilingüe para un parque en Italia y una app nativa para iPhone en la App Store.",
  "case.b1": "Sostenibilidad · Web", "case.b2": "Turismo · Web · IT/EN", "case.b3": "Productividad · iPhone",
  "case.c1p": "Página web para una empresa de economía circular: gestión de residuos de construcción y ecomateriales en Perú.",
  "case.c2p": "Sitio bilingüe (IT/EN) para una asociación italiana de jardines y mariposas: reservas, suscripciones y galería.",
  "case.c3p": "App nativa para iPhone: alarmas inteligentes según tu agenda. En 2 toques eliges el evento y cuántos minutos antes despertar.",

  "testi.eyebrow": "04 · Testimonios", "testi.title": "Lo que dicen los negocios que confiaron en nosotros.",
  "testi.desc": "Relaciones de largo plazo con dueños, gerentes y emprendedores. Pocos clientes, mucho compromiso.",
  "testi.q1": "Entendieron mi negocio desde el primer día. Entregaron en tres meses lo que llevaba un año detenido.",
  "testi.q2": "Ahora todo funciona solo. Dejamos de apagar incendios y empezamos a crecer.",
  "testi.q3": "Pasamos de una idea a una app real en producción, con datos que entiendo y puedo presentar a mi directorio.",

  "price.eyebrow": "05 · Precios", "price.title": "Tres maneras de trabajar juntos.",
  "price.desc": "Por proyecto cerrado, con un equipo dedicado o mantenimiento mensual. Sin costos escondidos y todo conversado antes de empezar.",
  "price.from": "desde", "price.month": "/ mes", "price.custom": "A medida",
  "price.p1h": "Inicio", "price.p1t": "Proyecto cerrado", "price.p1d": "Tu primera página web o app, lista para usar y crecer con tu negocio.",
  "price.p1f1": "1 web o app móvil", "price.p1f2": "Diseño + desarrollo + publicación", "price.p1f3": "Hosting en la nube incluido", "price.p1f4": "Entrega en 4–8 semanas",
  "price.p1c": "Pedir propuesta",
  "price.p2h": "Crecimiento", "price.p2t": "Equipo a tu medida", "price.p2d": "Un equipo trabajando contigo todos los meses para construir y mejorar tu plataforma.",
  "price.p2f1": "Equipo de 3–5 personas", "price.p2f2": "Reuniones y avances cada semana", "price.p2f3": "Web + app + IA si lo necesitas", "price.p2f4": "Compromiso mínimo 3 meses",
  "price.p2c": "Reservar equipo",
  "price.p3h": "Empresarial", "price.p3t": "Soporte continuo", "price.p3d": "Mantenimiento y mejoras continuas para tu plataforma, con soporte cuando lo necesites.",
  "price.p3f1": "Soporte priorizado", "price.p3f2": "Atención cuando lo necesites", "price.p3f3": "Mejoras y nuevas funciones", "price.p3f4": "Reportes mensuales claros",
  "price.p3c": "Hablar con nosotros",

  "ct.eyebrow": "06 · Contacto", "ct.title": "Cuéntanos sobre tu negocio.",
  "ct.desc": "Te respondemos en menos de 24 horas hábiles con una primera evaluación honesta de qué necesitas, cuánto demora y cuánto cuesta.",
  "ct.info": "// Hablemos", "ct.h": "Conversemos, sin intermediarios.", "ct.p": "Escríbenos, llámanos o agenda una reunión. Trabajamos remoto desde Lima — Perú.",
  "ct.lblPhone": "Teléfono · WhatsApp", "ct.lblMail": "Correo", "ct.lblRuc": "RUC",
  "ct.fName": "Tu nombre", "ct.fEmail": "Correo", "ct.fCompany": "Tu negocio", "ct.fService": "¿Qué necesitas?",
  "ct.fOpt1": "Página o tienda web", "ct.fOpt2": "App para celular", "ct.fOpt3": "Automatización con IA",
  "ct.fOpt4": "Mantenimiento y soporte", "ct.fOpt5": "Migrar mi negocio a la nube", "ct.fOpt6": "No estoy seguro · necesito asesoría",
  "ct.fMsg": "Cuéntanos sobre tu proyecto", "ct.fNote": "Respondemos en < 24h hábiles", "ct.fSend": "Enviar mensaje",

  "foot.blurb": "Hacemos software a la medida de tu negocio. Páginas, apps, automatización con IA y soporte continuo.",
  "foot.s1": "Servicios", "foot.s1a": "Páginas y tiendas web", "foot.s1b": "Apps móviles", "foot.s1c": "Automatización con IA", "foot.s1d": "Mantenimiento y soporte", "foot.s1e": "Migración a la nube",
  "foot.s2": "Negocio", "foot.s2a": "Cómo trabajamos", "foot.s2b": "Proyectos", "foot.s2c": "Precios", "foot.s2d": "Contacto",
  "foot.s3": "Contacto", "foot.rights": "Todos los derechos reservados",

  "mod.eyebrow": "// Cotización rápida", "mod.h": "Empecemos tu proyecto.", "mod.p": "Déjanos tus datos y te contactamos en menos de 24 horas hábiles.",
  "mod.brief": "Cuéntanos brevemente", "mod.send": "Enviar y agendar reunión"
},

/* ---------------- BIZ · ENGLISH ---------------- */
"biz-en": {
  "nav.services": "Services", "nav.process": "How we work", "nav.cases": "Projects", "nav.pricing": "Pricing", "nav.contact": "Contact", "nav.cta": "Get a quote",
  "aud.biz": "Business", "aud.tech": "Technical",

  "hero.eyebrow": "Software to grow your business · Lima, Peru",
  "hero.h1a": "We build", "hero.h1b": "the software", "hero.h1c": "your business needs to grow.",
  "hero.lead": "Websites, online stores, mobile apps and AI automation. We walk with you from idea to the day your customers are already using it.",
  "hero.cta1": "Let's talk about your project", "hero.cta2": "See what we do",
  "hero.m1": "Years helping businesses", "hero.m2": "Industries we serve", "hero.m3": "Types of solutions", "hero.m4": "Ongoing support",

  "trustBiz.label": "// Industries we serve",
  "trustBiz.c1": "Retail", "trustBiz.c2": "Restaurants", "trustBiz.c3": "Professional services",
  "trustBiz.c4": "Health & clinics", "trustBiz.c5": "Education", "trustBiz.c6": "Real estate",
  "trustBiz.c7": "Logistics & delivery", "trustBiz.c8": "Startups & founders",

  "bh.eyebrow": "// What you get",
  "bh.title": "Your business, ready for the internet.",
  "bh.i1t": "Your website or online store", "bh.i1d": "Built to sell, fast and easy to update yourself.",
  "bh.i2t": "Your mobile app",             "bh.i2d": "On the App Store and Google Play, ready for your customers.",
  "bh.i3t": "AI that saves you time",      "bh.i3d": "Chatbots, automations and WhatsApp auto-replies.",
  "bh.i4t": "Support when you need it",    "bh.i4d": "Maintenance, improvements and continuous backup. No surprises.",
  "bh.p1": "years", "bh.p2": "typical weeks", "bh.p3": "Ongoing support",

  "svc.eyebrow": "01 · What we do", "svc.title": "Five solutions to grow your business.",
  "svc.desc": "We're with you start to finish: idea, design, build, launch and support. No middlemen and no fine print.",
  "svc.tab1": "Websites & online stores", "svc.tab2": "Mobile apps", "svc.tab3": "AI automation", "svc.tab4": "Maintenance & support", "svc.tab5": "Your business on the cloud",
  "svc.stackLabel": "What's included",

  "svc.web.eyebrow": "Your web presence", "svc.web.h": "A website or online store built to sell.",
  "svc.web.p": "Modern, fast and easy to update. Mobile-ready, optimized for Google and with all the integrations your business needs.",
  "svc.web.f1": "Brand website or full online store",
  "svc.web.f2": "Online payments (Niubiz, Culqi, MercadoPago, Izipay)",
  "svc.web.f3": "Admin panel so you can update prices and products yourself",
  "svc.web.f4": "Google ranking and fast loading speed",
  "svc.web.b1": "Brand website", "svc.web.b2": "Online store", "svc.web.b3": "Admin panel",
  "svc.web.b4": "Online payments", "svc.web.b5": "Google SEO", "svc.web.b6": "Hosting included",

  "svc.mob.eyebrow": "Mobile apps", "svc.mob.h": "Your business in your customers' pocket.",
  "svc.mob.p": "Professional apps for iPhone and Android: orders, bookings, loyalty, delivery — whatever your business needs. We publish them on the official stores.",
  "svc.mob.f1": "iPhone app (App Store) and Android (Play Store)",
  "svc.mob.f2": "Notifications, in-app payments and biometric login",
  "svc.mob.f3": "Store publishing and version support",
  "svc.mob.f4": "Design your customers understand right away",
  "svc.mob.b1": "iPhone app", "svc.mob.b2": "Android app", "svc.mob.b3": "Push notifications",
  "svc.mob.b4": "Biometric login", "svc.mob.b5": "In-app payments", "svc.mob.b6": "Store publishing",

  "svc.ai.eyebrow": "Practical AI", "svc.ai.h": "Automate tasks and serve your customers 24/7.",
  "svc.ai.p": "Chatbots that actually understand, assistants that reply on WhatsApp, systems that classify documents, recommend products or summarize meetings. Applied AI, not hype.",
  "svc.ai.f1": "Smart chatbots for WhatsApp and your website",
  "svc.ai.f2": "Smart search across your documents and emails",
  "svc.ai.f3": "Automatic summary and classification of information",
  "svc.ai.f4": "Data analysis and sales predictions",
  "svc.ai.b1": "WhatsApp chatbot", "svc.ai.b2": "24/7 service", "svc.ai.b3": "Email summary",
  "svc.ai.b4": "Smart search", "svc.ai.b5": "Sales prediction", "svc.ai.b6": "Recommendations",

  "svc.dev.eyebrow": "Maintenance, no surprises", "svc.dev.h": "Your system always running, without you having to worry.",
  "svc.dev.p": "We keep your site, app and systems running 24/7. We catch problems before your customers do and handle updates and backups.",
  "svc.dev.f1": "Continuous monitoring and automatic backups",
  "svc.dev.f2": "Monthly security updates",
  "svc.dev.f3": "Fast response if something fails",
  "svc.dev.f4": "Clear monthly reports, in plain language",
  "svc.dev.b1": "24/7 monitoring", "svc.dev.b2": "Auto backups", "svc.dev.b3": "Updates",
  "svc.dev.b4": "Security", "svc.dev.b5": "Monthly reports", "svc.dev.b6": "Fast response",

  "svc.cloud.eyebrow": "Your business on the cloud", "svc.cloud.h": "Your systems, data and files safe and reachable.",
  "svc.cloud.p": "We move your business to the big cloud providers (AWS, Azure or Google). Your data backed up, your team working from anywhere, with controlled costs.",
  "svc.cloud.f1": "Migration of your systems to the cloud",
  "svc.cloud.f2": "Secure backup of all your information",
  "svc.cloud.f3": "Access from anywhere and any device",
  "svc.cloud.f4": "Monthly cost control with no surprises",
  "svc.cloud.b1": "Cloud migration", "svc.cloud.b2": "Secure backup", "svc.cloud.b3": "Remote access",
  "svc.cloud.b4": "Cost control", "svc.cloud.b5": "Corporate email", "svc.cloud.b6": "Shared files",

  "proc.eyebrow": "02 · How we work", "proc.title": "A simple process, no technical knots.",
  "proc.desc": "Five clear steps. You choose how involved to be and we handle the technical side.",
  "proc.n1": "01 / WE LISTEN", "proc.n2": "02 / WE DESIGN", "proc.n3": "03 / WE BUILD", "proc.n4": "04 / WE LAUNCH", "proc.n5": "05 / WE SUPPORT",
  "proc.s1h": "We listen", "proc.s1p": "We talk about your business, your customers and what you want to achieve. You get a clear proposal with timeline and cost.",
  "proc.s2h": "We design", "proc.s2p": "We show you how your site or app will look before we start building. We adjust until you love it.",
  "proc.s3h": "We build", "proc.s3p": "We build in stages and show you progress every week. You review and approve.",
  "proc.s4h": "We launch", "proc.s4p": "We deploy everything to the cloud and publish to the stores if it's an app. We're there with you on launch day.",
  "proc.s5h": "We support", "proc.s5p": "We provide support, updates and improvements. If something breaks, we fix it fast.",

  "case.eyebrow": "03 · Projects", "case.title": "Real products people use.",
  "case.desc": "A small sample of projects we've launched: a circular-economy platform in Peru, a bilingual park website in Italy, and a native iPhone app on the App Store.",
  "case.b1": "Sustainability · Web", "case.b2": "Tourism · Web · IT/EN", "case.b3": "Productivity · iPhone",
  "case.c1p": "Website for a circular-economy company: construction waste management and eco-materials in Peru.",
  "case.c2p": "Bilingual (IT/EN) website for an Italian gardens and butterflies association: bookings, subscriptions and gallery.",
  "case.c3p": "Native iPhone app: smart alarms based on your calendar. In 2 taps you pick the event and how many minutes before to wake.",

  "testi.eyebrow": "04 · Testimonials", "testi.title": "What the businesses who trusted us say.",
  "testi.desc": "Long-term relationships with owners, managers and entrepreneurs. Few clients, deep commitment.",
  "testi.q1": "They understood my business from day one. Delivered in three months what had been stuck for a year.",
  "testi.q2": "Now everything just works. We stopped firefighting and started growing.",
  "testi.q3": "We went from an idea to a real app in production, with data I actually understand and can show my board.",

  "price.eyebrow": "05 · Pricing", "price.title": "Three ways to work together.",
  "price.desc": "Fixed-scope project, dedicated team or monthly support. No hidden costs and everything talked through up front.",
  "price.from": "from", "price.month": "/ mo", "price.custom": "Custom",
  "price.p1h": "Start", "price.p1t": "Fixed-scope project", "price.p1d": "Your first website or app, ready to use and grow with your business.",
  "price.p1f1": "1 web or mobile app", "price.p1f2": "Design + build + publishing", "price.p1f3": "Cloud hosting included", "price.p1f4": "Delivered in 4–8 weeks",
  "price.p1c": "Request a proposal",
  "price.p2h": "Growth", "price.p2t": "Team made to measure", "price.p2d": "A team working with you every month to build and improve your platform.",
  "price.p2f1": "Team of 3–5 people", "price.p2f2": "Meetings and progress every week", "price.p2f3": "Web + app + AI if you need", "price.p2f4": "3-month minimum commitment",
  "price.p2c": "Reserve team",
  "price.p3h": "Enterprise", "price.p3t": "Ongoing support", "price.p3d": "Continuous maintenance and improvements for your platform, with support whenever you need it.",
  "price.p3f1": "Priority support", "price.p3f2": "Help when you need it", "price.p3f3": "Improvements and new features", "price.p3f4": "Clear monthly reports",
  "price.p3c": "Talk to us",

  "ct.eyebrow": "06 · Contact", "ct.title": "Tell us about your business.",
  "ct.desc": "We reply in less than 24 business hours with an honest first read on what you need, how long it takes and how much it costs.",
  "ct.info": "// Let's talk", "ct.h": "Let's talk, no middlemen.", "ct.p": "Write, call or schedule a meeting. We work remote from Lima — Peru.",
  "ct.lblPhone": "Phone · WhatsApp", "ct.lblMail": "Email", "ct.lblRuc": "Tax ID",
  "ct.fName": "Your name", "ct.fEmail": "Email", "ct.fCompany": "Your business", "ct.fService": "What do you need?",
  "ct.fOpt1": "Website or online store", "ct.fOpt2": "Mobile app", "ct.fOpt3": "AI automation",
  "ct.fOpt4": "Maintenance & support", "ct.fOpt5": "Move my business to the cloud", "ct.fOpt6": "Not sure · I need advice",
  "ct.fMsg": "Tell us about your project", "ct.fNote": "We reply in < 24 business hours", "ct.fSend": "Send message",

  "foot.blurb": "Custom software for your business. Websites, apps, AI automation and ongoing support.",
  "foot.s1": "Services", "foot.s1a": "Websites & online stores", "foot.s1b": "Mobile apps", "foot.s1c": "AI automation", "foot.s1d": "Maintenance & support", "foot.s1e": "Cloud migration",
  "foot.s2": "Business", "foot.s2a": "How we work", "foot.s2b": "Projects", "foot.s2c": "Pricing", "foot.s2d": "Contact",
  "foot.s3": "Contact", "foot.rights": "All rights reserved",

  "mod.eyebrow": "// Quick quote", "mod.h": "Let's start your project.", "mod.p": "Leave your info and we'll reach out in less than 24 business hours.",
  "mod.brief": "Tell us briefly", "mod.send": "Send and schedule meeting"
}

};
